#!/bin/bash
set -ueo pipefail

SEL4CP_TAG=sel4cp-container

_docker-build() {
    docker buildx build -t "$SEL4CP_TAG" -f Dockerfile .
}

shell() {
    docker run --rm -ti -v "$(pwd)/tmp:/sel4cp/tmp" --entrypoint bash "$SEL4CP_TAG"
}

entrypoint() {
    docker run --rm -ti -v "$(pwd)/tmp:/sel4cp/tmp" "$SEL4CP_TAG" "$@"
}

_docker-build
"$@"
