#!/bin/bash
set -ueo pipefail

IMG=sel4cp-container

_docker-build() {
    docker buildx build -t "$IMG" .
}

shell() {
    docker run --rm -ti -v "$(pwd)/tmp:/sel4cp/tmp" --entrypoint bash "$IMG"
}

build() {
    docker run --rm -ti -v "$(pwd)/tmp:/sel4cp/tmp" "$IMG" "$@"
}

_docker-build
"$@"
